version: '3.9'

services:
  api:
    build: .
    container_name: hotel_management_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always